# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Projects/sjtrax/project_1/project_1.srcs/sources_1/ip/map_mem/map_mem.xci
# IP: The module: 'map_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Projects/sjtrax/project_1/project_1.srcs/sources_1/ip/map_mem/map_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'map_mem'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: C:/Projects/sjtrax/project_1/project_1.srcs/sources_1/ip/map_mem/map_mem.xci
# IP: The module: 'map_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Projects/sjtrax/project_1/project_1.srcs/sources_1/ip/map_mem/map_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'map_mem'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
