# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7vx485tffg1761-2

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Projects/sjtrax/project_1/project_1.cache/wt [current_project]
set_property parent.project_path C:/Projects/sjtrax/project_1/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part xilinx.com:vc707:part0:1.1 [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
add_files -quiet C:/Projects/sjtrax/project_1/project_1.runs/ila_uart_synth_1/ila_uart.dcp
set_property used_in_implementation false [get_files C:/Projects/sjtrax/project_1/project_1.runs/ila_uart_synth_1/ila_uart.dcp]
add_files -quiet C:/Projects/sjtrax/project_1/project_1.runs/uart_tx_fifo_synth_1/uart_tx_fifo.dcp
set_property used_in_implementation false [get_files C:/Projects/sjtrax/project_1/project_1.runs/uart_tx_fifo_synth_1/uart_tx_fifo.dcp]
add_files -quiet C:/Projects/sjtrax/project_1/project_1.runs/vio_uart_synth_1/vio_uart.dcp
set_property used_in_implementation false [get_files C:/Projects/sjtrax/project_1/project_1.runs/vio_uart_synth_1/vio_uart.dcp]
add_files -quiet C:/Projects/sjtrax/project_1/project_1.runs/uartmon_fifo_synth_1/uartmon_fifo.dcp
set_property used_in_implementation false [get_files C:/Projects/sjtrax/project_1/project_1.runs/uartmon_fifo_synth_1/uartmon_fifo.dcp]
add_files -quiet C:/Projects/sjtrax/project_1/project_1.runs/vio_uartmon_ctrl_synth_1/vio_uartmon_ctrl.dcp
set_property used_in_implementation false [get_files C:/Projects/sjtrax/project_1/project_1.runs/vio_uartmon_ctrl_synth_1/vio_uartmon_ctrl.dcp]
add_files -quiet C:/Projects/sjtrax/project_1/project_1.runs/ila_uartmon_synth_1/ila_uartmon.dcp
set_property used_in_implementation false [get_files C:/Projects/sjtrax/project_1/project_1.runs/ila_uartmon_synth_1/ila_uartmon.dcp]
add_files -quiet C:/Projects/sjtrax/project_1/project_1.runs/map_mem_synth_1/map_mem.dcp
set_property used_in_implementation false [get_files C:/Projects/sjtrax/project_1/project_1.runs/map_mem_synth_1/map_mem.dcp]
add_files -quiet C:/Projects/sjtrax/project_1/project_1.runs/vio_botctrl_synth_1/vio_botctrl.dcp
set_property used_in_implementation false [get_files C:/Projects/sjtrax/project_1/project_1.runs/vio_botctrl_synth_1/vio_botctrl.dcp]
add_files -quiet C:/Projects/sjtrax/project_1/project_1.runs/vio_receivedata_synth_1/vio_receivedata.dcp
set_property used_in_implementation false [get_files C:/Projects/sjtrax/project_1/project_1.runs/vio_receivedata_synth_1/vio_receivedata.dcp]
add_files -quiet C:/Projects/sjtrax/project_1/project_1.runs/ila_notes_synth_1/ila_notes.dcp
set_property used_in_implementation false [get_files C:/Projects/sjtrax/project_1/project_1.runs/ila_notes_synth_1/ila_notes.dcp]
read_vhdl -library xil_defaultlib {
  C:/Projects/mish_vhdl/mish_div.vhd
  C:/Projects/sjtrax/src/uartmon.vhd
  C:/Projects/sjtrax/src/tx_led.vhd
  C:/Projects/sjtrax/src/traxif.vhd
  C:/Projects/mish_vhdl/mish_uart.vhd
  C:/Projects/sjtrax/src/bot2.vhd
  C:/Projects/sjtrax/src/sjtrax.vhd
  C:/Projects/mish_vhdl/mish_simple_arbiter.vhd
  C:/Projects/mish_vhdl/mish_prbs15.vhd
  C:/Projects/sjtrax/src/initialcom.vhd
  C:/Projects/sjtrax/src/mapmem.vhd
  C:/Projects/sjtrax/src/lookup.vhd
  C:/Projects/sjtrax/src/getaroundcolors.vhd
  C:/Projects/sjtrax/src/scan_forced.vhd
  C:/Projects/sjtrax/src/opposite_color.vhd
  C:/Projects/sjtrax/src/is_prohibited_3.vhd
  C:/Projects/sjtrax/src/is_consistent_placement.vhd
  C:/Projects/sjtrax/src/is_isolated.vhd
  C:/Projects/sjtrax/src/color_the_tile.vhd
  C:/Projects/sjtrax/src/map_mem_w.vhd
  C:/Projects/sjtrax/src/rnd_note_gen.vhd
  C:/Projects/sjtrax/src/board_area.vhd
}
read_xdc C:/Projects/sjtrax/src/VC707_rev_2.0.ucf.xdc
set_property used_in_implementation false [get_files C:/Projects/sjtrax/src/VC707_rev_2.0.ucf.xdc]

synth_design -top sjtrax -part xc7vx485tffg1761-2
write_checkpoint -noxdef sjtrax.dcp
catch { report_utilization -file sjtrax_utilization_synth.rpt -pb sjtrax_utilization_synth.pb }
