# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Projects/sjtrax/project_1/project_1.srcs/sources_1/ip/uartmon_fifo/uartmon_fifo.xci
# IP: The module: 'uartmon_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Projects/sjtrax/project_1/project_1.srcs/sources_1/ip/uartmon_fifo/uartmon_fifo/uartmon_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'uartmon_fifo'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Projects/sjtrax/project_1/project_1.srcs/sources_1/ip/uartmon_fifo/uartmon_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'uartmon_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: C:/Projects/sjtrax/project_1/project_1.srcs/sources_1/ip/uartmon_fifo/uartmon_fifo.xci
# IP: The module: 'uartmon_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Projects/sjtrax/project_1/project_1.srcs/sources_1/ip/uartmon_fifo/uartmon_fifo/uartmon_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'uartmon_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Projects/sjtrax/project_1/project_1.srcs/sources_1/ip/uartmon_fifo/uartmon_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'uartmon_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
